import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import data from '../data/education.json'
import { useState } from 'react'
import Card from '../components/Card'
import Link from 'next/Link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
   console.log(data);
   const [information, setInformation] = useState([...data])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            <Link href="about">About</Link>
          </p>
        
        </div>
        <Image style={{display:'flex', justifyContent:'center', alignItems:'center', marginBottom:50}}
        src="/theoffice.png"
        width="400"
        height="200"
        alt="office"
       />
        <div className={styles.grid}>
        <b>Computing Degrees:</b>
        {information && information.map((info, index) => {
          if(info.department === "Computing"){
            return (
              <Card key={index} degree={info.degree}  colour="dark blue" font="20px"/>
            )
          }
        })}

        <b>Business Degrees:</b>
        {information && information.map((info, index) => {
          if(info.department === "Business"){ 
            return (
              <Card key={index} degree={info.degree} colour="dark green" font="20px"/>
            )
          }
        })}
      </div>
      </main>
    </>
  )
}
